# DS 3000 HW 1 

Due: Tuesday Sep 17 @ 11:59 PM EST

### Submission Instructions
Submit this `ipynb` file to Gradescope (this can also be done via the assignment on Canvas).  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to gradescope.

### Tips for success
- Start early
- Make use of Piazza (also accessible through Canvas)
- Make use of Office Hours
- Remember to use cells and headings to make the notebook easy to read (if a grader cannot find the answer to a problem, you will receive no points for it)
- Under no circumstances may one student view or share their ungraded homework or quiz with another student [(see also)](http://www.northeastern.edu/osccr/academic-integrity), though you are welcome to **talk about** (*not* show each other your answers to) the problems.

# Part 1 (25 points): Markdown in Jupyter

Use the markdown language below to create your own brief wikipedia-esque description of any subject of interest. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a markdown table of size at least 3 rows x 3 columns (needn't be correct, but must make sense)
- a list (i.e. of bullet points, in markdown) with at least five items
- a working hyperlink to another website

Please be brief in your text.  Aim for only a few sentences of total of text.  We won't grade based on content, but keep it appropriate for class.  If you make the grader smile, no extra credit will be awarded beyond the satisfaction of having made somebody's day better :)

# Title 
## Subtitle
### SubSubTitle

### Image
[Python Logo](https://www.python.org/static/community_logos/python-logo-master-v3-TM.png)


### Table
| Column 1 | Column 2 | Column 3 |
|:------|--|-----:|
|  Row 1   |  Row 1   |  Row 1   |
|  Row 2   |  Row 2   |  Row 2   |
|  Row 3   |  Row 3   |  Row 3   |

### what makes a husky
- Be in northeastern 
- be a husky
- know PAWS
- do a CO OP
- pass OOD and ALGO

### hyperlink
[Link Text](https://www.northeastern.edu)




# Part 2: Lists and Flow and Functions, Oh my! 
## Part 2.1: Manual Data Entry (25 points)

**Beware**: to complete this part of the assignment, you *must* do it during a weekday when the stock market is open!

How would you collect data on a stock's performance without a computer doing it automatically? Go to [this website](https://www.tradingview.com/) and look up a stock (any stock). You are going to write a function that takes live input of the stock's value (entered by you), saves all inputs in a list, stops once you enter 10 values **or** three consecutive decreasing values (whichever comes first), and returns the values.

For this problem:

- Call your function `my_stock`
- Make sure that you use the `input()` option within your function to accept entries
- Make sure you are saving all entries in a list
- Use `if-else` and a `while` loop
- When you have written the function, call:

`manual_data_entry = my_stock()`

`manual_data_entry`

and click between (or have the pages open side by side) this notebook and the stock to manually enter the stock's value over time (the website updates every 5 seconds).

**Note**: There may be multiple ways to get this function to work, but to receive full points, your function **must** have the five components listed above (there may be more efficient ways to do it, but I want you to show me you know how to use *these methods*).

In [2]:
def my_stock():
    """
    Prompts the user to enter stock values until either 10 values are entered 
    or 3 consecutive decreasing values are entered. 

    The function keeps track of consecutive decreasing stock values and stops 
    collecting data if the condition is met before reaching 10 entries.

    Returns:
        list: A list of stock values entered by the user.
    """
    stock_values = []  # List to store the entered stock values
    consecutive_decreasing = 0  # Counter for consecutive decreasing values
    
    # Continue to collect stock values until either 10 values are entered
    # or there are 3 consecutive decreasing values
    while len(stock_values) < 10 and consecutive_decreasing < 3:   
        stock_values.append(float(input("Enter the stock value: ")))  
        
        # Check if the current value is less than the previous one
        if len(stock_values) > 1:
            if stock_values[-1] < stock_values[-2]: 
                consecutive_decreasing += 1  
            else:
                consecutive_decreasing = 0  
        
    return stock_values 

# Call the function and store the result
manual_data_entry = my_stock()

# Display the entered stock values
manual_data_entry


[10.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 0.0]

## Part 2.2: Thinking (5 pts)

In a markdown (text) cell, discuss at least **two** drawbacks to using the function you wrote in Part 2.1 to collect the data the way we did. Make sure you **discuss** the drawbacks, instead of simply listing them. What did we do that was sub-optimal and how could we improve it?

## Drawbacks

- **inputing data manually**: by inputing the data manually we are causing a delay between it actually getting changed in the stock market and getting inputed into the system, therefore, making the price data switch faster than we can implement it
- **catching errors**: if the stocks values gets a different value that isn't a float it will call for an error

# Part 3: Numpy
## Part 3.1: Creating Arrays (5 points)

Create the following two arrays using the NumPy library. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 42 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & 0 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

Then, uncomment out the code provided to print them and verify they are correct.

In [1]:
# make sure to import numpy library
import numpy as np

In [26]:
# Initializing array_a and array_b using numpy
array_a = np.array([(3,42,-2,3),(.5,-1,6,4),(-5,7,0,2)])
array_b = np.array([(42,38,34),(30,26,22),(18,14,10),(6,2,-2),(-6,-10,-14)])

In [24]:
#printing array_a
print(array_a)

[[ 3.  42.  -2.   3. ]
 [ 0.5 -1.   6.   4. ]
 [-5.   7.   0.   2. ]]


In [27]:
#printing array_b
print(array_b)

[[ 42  38  34]
 [ 30  26  22]
 [ 18  14  10]
 [  6   2  -2]
 [ -6 -10 -14]]


## Part 3.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b`, then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [34]:
# Part 1
# retriving the properties for array_a
shape_a = array_a.shape
size_a = array_a.size
ndim_a = array_a.ndim
nbytes_a = array_a.nbytes

# retriving the properties for array_b
shape_b = array_b.shape
size_b = array_b.size
ndim_b = array_b.ndim
nbytes_b = array_b.nbytes

# printing the properties
print(f"array_a - Shape: {shape_a}, Size: {size_a}, ndim: {ndim_a}, nbytes: {nbytes_a}")
print(f"array_b - Shape: {shape_b}, Size: {size_b}, ndim: {ndim_b}, nbytes: {nbytes_b}")

#Part 2
# transpose array_a and array_b
t_array_a = np.transpose(array_a)
t_array_b = np.transpose(array_b)

# printing array_a and array_b
print(t_array_a)
print(t_array_b)

#Part 3
# Add array_a and t_array_b
try: 
    sum_arrays = array_a + t_array_b
    print("Sum of the array_a and t_array_b \n", sum_arrays)
except Exception as e:
    print(f"ERROR adding array_a and t_array_b: {e}")

# Remove the last column of t_array_b and try again
t_array_b_modified = t_array_b[:, :-1]

# adding array_a and t_array_b_modified and printing
sum_modified = array_a + t_array_b_modified
print("Addition after removing the last column:\n", sum_modified)

Array A - Shape: (3, 4), Size: 12, ndim: 2, nbytes: 96
Array B - Shape: (5, 3), Size: 15, ndim: 2, nbytes: 120
[[ 3.   0.5 -5. ]
 [42.  -1.   7. ]
 [-2.   6.   0. ]
 [ 3.   4.   2. ]]
[[ 42  30  18   6  -6]
 [ 38  26  14   2 -10]
 [ 34  22  10  -2 -14]]
ERROR adding array_a and t_array_b: operands could not be broadcast together with shapes (3,4) (3,5) 
Addition after removing the last column:
 [[45.  72.  16.   9. ]
 [38.5 25.  20.   6. ]
 [29.  29.  10.   0. ]]


The error we are receving is because each arrea have a diferent size of rows/columns, while array_a had a shape of (3,4) array_b had a shape of (3,5), in order to be able to add them they need to have the same number of rows/columns. Therefore, for the code to run a try-expect was put in place

# Part 4: Pandas Pokémon
## Part 4.1: Reading in Data (5 points)

On Canvas is the `pokedata.csv` file. Read this data set in, using the `Pokedex` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [2]:
# make sure to import pandas library
import pandas as pd

In [9]:
# Reading the CSV
df = pd.read_csv("pokedata.csv")
# Getting the first 10
df_head = df.head(10)

# Printing it out
print (df_head)

   Pokedex     Pokemon MainType SecondaryType  Height  Weight  Damage  \
0        1   Bulbasaur    Grass        Poison      24    25.2      45   
1        2     Ivysaur    Grass        Poison      39    28.7      60   
2        3    Venusaur    Grass        Poison      79   220.5      80   
3        4  Charmander     Fire           NaN      24    18.7      39   
4        5  Charmeleon     Fire           NaN      43    41.9      58   
5        6   Charizard     Fire        Flying      67   199.5      78   
6        7    Squirtle    Water           NaN      20    19.8      45   
7        8   Wartortle    Water           NaN      39    49.6      59   
8        9   Blastoise    Water           NaN      63   188.5      79   
9       10    Caterpie      Bug           NaN      12     6.4      45   

   BaseSpeed  Attack  Defense  
0         45      49       49  
1         60      62       63  
2         80      82       83  
3         65      52       43  
4         80      64       58  
5   

## Part 4.2: Manipulating Data (20 points)

1. Add a new column to the data set that calculates the BMI of the Pokémon. The formula for BMI using Imperial Units (such as these data contain) is = $703 \times \frac{Weight}{Height^2}$. Print the first few rows.
    2. Use indexing and the `.idxmax()` and `.idxmin()` functions to find the Pokémon that have (a) the highest BMI and (b) the lowest BMI.
1. Create a subset of the Pokémon Data that you created in (1) which (a) includes only Pokémon that have `BaseSpeed >= 70` and (b) **excludes** all Pokémon with the Fire `MainType`. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the **full** Pokémon Data from the data from (1). Create a markdown cell and explain:
    2. What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [ ]:
def calculate_BMI(weight, height):
    height_modified = height * height
    return 703 * (weight/height_modified)